Feature/login/UI
NoWasteInMyFridge/NoWasteInMyFridge pull request #4
Opened 2023-12-28 18:03 UTC by pattanan-pr

-login
-navigation
-bottom navigation
-init screen (home, inventory, adding, setting)

2023-12-29 01:29 UTC, Jakarin-Jojo requested changes
ฝาก format code ทุกหน้าที่ทำ

2023-12-29 01:34 UTC, Jakarin-Jojo requested changes
ชื่อ folder เป็นพิมเล็ก

2023-12-29 01:49 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/MainActivity.kt
>  }
ไม่ใช้แล้วใช่ป่ะ ฝากลบหน่อย   
GreetingPreview ด้วยย

2023-12-29 01:50 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screen.kt
> +    object LoginScreen : Screen("login_screen")
ใช้เป็น data object

2023-12-29 01:53 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Adding.kt
> +            .background(color = Color(0xFFF4F5FB))// Set the background color to pink
ไม่ Hard code ไปใส่ ค่าไว้ใน `Color.kt` ก่อนก็ได้ แล้วใช้ผ่านตัวแปรเอา

2023-12-29 01:53 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Adding.kt
> +            .background(color = Color(0xFFF4F5FB))// Set the background color to pink
ลบ comment ออกด้วย

2023-12-29 01:54 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/HomeScreen.kt
> +            .background(color = Color(0xFFF4F5FB))
อันนี้ด้วย ไม่ Hard code

2023-12-29 02:02 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Adding.kt
> +    }
ฝากลบออกหน่อย ค่อยไปเพิ่มตอนทำ feature นี้ ดีกว่า

2023-12-29 02:03 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/HomeScreen.kt
> +    }
อันนี้ด้วย

2023-12-29 02:03 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Inventory.kt
> +    }
อันนี้ด้วย

2023-12-29 02:38 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/MainScreen.kt
> +//        },
อันนี้สงสัยอ่ะ ต้องใช้ไหมนะ

2023-12-29 02:44 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Navigation.kt
> +
ใส่ 
```kotlin
@Preview
```

2023-12-29 03:06 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Setting.kt
> +    }
ฝากลบด้วย ค่อยทำทีหลัง

2023-12-29 03:08 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/MainScreen.kt
> +        contentColor = Color(0xFF888888),
ไม่ Hard code เอาไปใส่` Color.kt` ละเรียกใช้ผ่านตัวแปร

2023-12-29 03:35 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/ui/theme/BottomBarScreen.kt
> +    )
```suggestion
    val route: String,
    val title: String,
    val icon: ImageVector,
    ){
    data object Home: BottomBarScreen(
        route = "home",
        title = "Home",
        icon = Icons.Default.Home,
    )
    data object Inventory: BottomBarScreen(
        route = "inventory",
        title = "Inventory",
        icon = Icons.Default.List,
    )
    data object Adding: BottomBarScreen(
        route = "adding",
        title = "Adding",
        icon = Icons.Default.Add,
    )
    data object Setting: BottomBarScreen(
        route = "setting",
        title = "Setting",
        icon = Icons.Default.AccountCircle,
    )
```

2023-12-29 03:36 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +//            }
ถ้าไม่ใช้ก็ลบเลยย

2023-12-29 03:36 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +//                Spacer(modifier = Modifier.height(16.dp))
ถ้าไม่ใช้ก็ลบเลยย

2023-12-29 03:36 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +//                Text(text = "Log in")
ถ้าไม่ใช้ก็ลบเลยย

2023-12-29 03:36 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +//            Spacer(modifier = Modifier.height(16.dp))
ถ้าไม่ใช้ก็ลบเลยย

2023-12-29 03:46 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +                text = "Welcome",
ไม่  harcode ไปใส่ไว้ใน string.xml

2023-12-29 03:47 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +                    label = { Text(text = "Username") }
ไม่  harcode ไปใส่ไว้ใน string.xml

2023-12-29 03:47 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +                    label = { Text(text = "Password") },
ไม่  harcode ไปใส่ไว้ใน string.xml

2023-12-29 03:47 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +            Text(text = "forget your password?")
ไม่  harcode ไปใส่ไว้ใน string.xml

2023-12-29 03:48 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +            Text(text = "Don’t have account, sign-in")
ไม่  harcode ไปใส่ไว้ใน string.xml

2023-12-29 03:48 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Login/LoginScreen.kt
> +                Text(text = "LOGIN")
ไม่  harcode ไปใส่ไว้ใน string.xml

2024-01-02 00:19 UTC, Jakarin-Jojo commented on app/src/main/res/drawable/bottompart.png
เอาไปใส่ใน mipmap แล้ว คูณ 1,1.5,2,3,4 ตามลำดับ
![image](https://github.com/NoWasteInMyFridge/NoWasteInMyFridge/assets/72879083/ca5f08f2-2763-47cf-9a5b-aedeea5efb09)

2024-01-02 00:20 UTC, Jakarin-Jojo commented on app/src/main/res/drawable/toppart.png
เอาอันนี้ไปใส่ใน mipmap ด้วยยย

2024-01-02 04:08 UTC, Jakarin-Jojo commented
ฝากใส่ .idea ใน gitignore ด้วยยยย
และลบ .idea ละpush ขึ้นมาด้วยย

2024-01-03 18:21 UTC, pattanan-pr commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Adding.kt
> +    }
สี backgroundอ่ะ ไม่งั้นแยกไม่ออก

2024-01-03 18:22 UTC, pattanan-pr commented on app/src/main/java/com/develop/nowasteinmyfridge/Navigation.kt
> +
ยังไงนะ

2024-01-03 18:56 UTC, pattanan-pr commented on app/src/main/res/drawable/bottompart.png
ไม่แน่ใจอ่ะ ลองดูหน่อย

2024-01-06 04:39 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Navigation.kt
> +
ใส่ @Preview ตรงนี้

2024-01-06 04:53 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Screens/Adding.kt
> +    }
ก็มัน link ไว้อยู่แล้วป่ะตอนทำก็มาทำที่ file นี้
มันไม่สับสนมั้งงง

2024-01-06 04:54 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/Navigation.kt
> +
มันเอาไว้ Preview  ui แทน แบบ xml อ่ะ 
อยากให้ใส่ทุกอันที่ใส่ได้อ่ะ

2024-01-06 04:55 UTC, Jakarin-Jojo commented on app/src/main/res/drawable/bottompart.png
หมายถึงว่ายังไม่เข้าใจป่ะ

2024-01-06 06:37 UTC, pattanan-pr commented
ตอนนี้ใช้แบบเดิมอ่ะ ในโฟลเดอร์มันไม่เหมือนกันอ่ะ


เมื่อ ส. 6 ม.ค. 2567 เวลา 11:55 Jakarin Chujan ***@***.***>
เขียนว่า:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On app/src/main/res/drawable/bottompart.png
> <https://github.com/NoWasteInMyFridge/NoWasteInMyFridge/pull/4#discussion_r1443622519>
> :
>
> หมายถึงว่ายังไม่เข้าใจป่ะ
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NoWasteInMyFridge/NoWasteInMyFridge/pull/4#discussion_r1443622519>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASTYJ6644OVZ2EWONUYNI5DYNDKLZAVCNFSM6AAAAABBFYJFJOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMBXGIZTINBQGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-06 18:33 UTC, Jakarin-Jojo commented on app/src/main/res/drawable/bottompart.png
ลองปรับเป็นแบบนี้ก็น่าจะเห็นนะ
![image](https://github.com/NoWasteInMyFridge/NoWasteInMyFridge/assets/72879083/5181170c-c569-4e12-9633-961a6d991de4)

2024-01-06 18:49 UTC, Jakarin-Jojo commented on app/src/main/java/com/develop/nowasteinmyfridge/MainActivity.kt
>  }
อันนี้ก็ไม่ได้ใช้ป่ะ ลบเลย

2024-01-08 20:25 UTC, Jakarin-Jojo approved these changes, later dismissed

2024-01-08 20:35 UTC, Jakarin-Jojo approved these changes, later dismissed
Approved

2024-01-08 20:41 UTC, Jakarin-Jojo approved these changes

2024-01-09 02:51 UTC, merged